export const ADD_PRODUCTS_REQUEST = "ADD_PRODUCTS_REQUEST";
export const ADD_PRODUCTS_REQUEST_SUCCESS = "ADD_PRODUCTS_REQUEST_SUCCESS";
export const ADD_PRODUCTS_REQUEST_FAILURE = "ADD_PRODUCTS_REQUEST_FAILURE";

export const EDIT_PRODUCTS_REQUEST = "EDIT_PRODUCTS_REQUEST";
export const EDIT_PRODUCTS_REQUEST_SUCCESS = "EDIT_PRODUCTS_REQUEST_SUCCESS";
export const EDIT_PRODUCTS_REQUEST_FAILURE = "EDIT_PRODUCTS_REQUEST_FAILURE";

export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST";
export const DELETE_PRODUCTS_REQUEST_SUCCESS =
  "DELETE_PRODUCTS_REQUEST_SUCCESS";
export const DELETE_PRODUCTS_REQUEST_FAILURE =
  "DELETE_PRODUCTS_REQUEST_FAILURE";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_REQUEST_SUCCESS = "PRODUCT_DETAIL_REQUEST_SUCCESS";
export const PRODUCT_DETAIL_REQUEST_FAILURE = "PRODUCT_DETAIL_REQUEST_FAILURE";

export const CLEAR_PRODUCT_DATA = "CLEAR_PRODUCT_DATA";
