export const FETCH_ALL_PRODUCTS_REQUEST = "FETCH_ALL_PRODUCTS_REQUEST";
export const FETCH_ALL_PRODUCTS_REQUEST_SUCCESS =
  "FETCH_ALL_PRODUCTS_REQUEST_SUCCESS";
export const FETCH_ALL_PRODUCTS_REQUEST_FAILURE =
  "FETCH_ALL_PRODUCTS_REQUEST_FAILURE";

export const FETCH_CATEGORY_PRODUCTS_REQUEST =
  "FETCH_CATEGORY_PRODUCTS_REQUEST";
export const FETCH_CATEGORY_PRODUCTS_REQUEST_SUCCESS =
  "FETCH_CATEGORY_PRODUCTS_REQUEST_SUCCESS";
export const FETCH_CATEGORY_PRODUCTS_REQUEST_FAILURE =
  "FETCH_CATEGORY_PRODUCTS_REQUEST_FAILURE";
